service: datatracker
app: datatracker
tenant: dsykes


provider:
  name: aws
  runtime: nodejs6.10
  environment:
    PORT: ${env:PORT}
    SECRET: ${env:SECRET}
    ACCESS_KEY: ${env:ACCESS_KEY}
    SECRET_KEY: ${env:SECRET_KEY}

package:
  include:
  - ../node_modules/**

functions:
  app:
    handler: app.handler
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'