service: datatracker
app: datatracker
tenant: dsykes


provider:
  name: aws
  runtime: nodejs6.10
  environment:
    HOST: ${env:HOST}
    PORT: ${env:PORT}
    USER: ${env:USER}
    PASSWORD: ${env:PASSWORD}
    DB_NAME: ${env:DB_NAME}
    SECRET: ${env:SECRET}


functions:
  app:
    handler: app.handler
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'